# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 22:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jobid',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AddField(
            model_name='job',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 10, 22, 15, 33, 686013)),
        ),
        migrations.AlterField(
            model_name='job',
            name='input_file',
            field=models.FileField(upload_to='./tmp_files/'),
        ),
    ]
