# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0002_auto_20170210_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='submit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
