# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0003_auto_20170210_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='output_file',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
