# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 00:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0004_job_output_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='output_file',
        ),
    ]
