# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 20:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0007_auto_20170211_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 25, 20, 20, 44, 444218, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 11, 20, 20, 44, 444191, tzinfo=utc)),
        ),
    ]
