# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 21:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0008_auto_20170211_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 25, 21, 43, 41, 632079, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='input_file',
            field=models.FileField(upload_to='./input/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 11, 21, 43, 41, 632048, tzinfo=utc)),
        ),
    ]
