# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 21:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0009_auto_20170211_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='output_file_path',
            field=models.CharField(default='./output/tmp.out', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 25, 21, 53, 23, 148506, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 11, 21, 53, 23, 148474, tzinfo=utc)),
        ),
    ]
